###################################################################
#                                                                 #
#  Дополнительные настройки проекта для непрерывной интеграции.   #
#  В общем случае должны быть установлены в значения по умолчаню  #
#                                                                 #
###################################################################

variables:

  # [ON] Включить отчет о покрытии тестами (отображается в запросах на слиение)
  CODE_COVERAGE: "ON"

  # [ON] Включить расширенные опции предупреждений для всех веток
  EXTRA_WARNINGS: "ON"

  # [ON] Включить пароидальный уровень предупреждений для master
  PARANOID_WARNING: "ON"

  # [OFF] Сборка в статике или динамике
  BUILD_SHARED_LIBS: "OFF"

  # [ON] Собирать тесты 
  BUILD_TESTING: "ON"

  # [OFF] Позволить собмодулям опережать свою master-ветку 
  ALLOW_AHEAD_MASTER: "OFF"
