function(extended_option wname)
  set(wopt "${${wname}}")
  
  if ( NOT DEFINED ${wname} )
    if ( DEFINED ARGV2 )
      set(wopt ${ARGV2})
    elseif(DEFINED ARGV1)
      set(wopt ${ARGV1})
    else()
      set(wopt ON)
    endif()
  endif()

  if ( ${wopt} )
    message(STATUS "Set additional option ${wname}: ${wopt} ${desc} " )
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${wname}" PARENT_SCOPE)
  endif()
endfunction()
