name: C/C++ CI

on: 
  push:
    branches:
      - mambaru
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: setup
      run: |
        sudo apt-get install -y valgrind
        git config --global user.email "migashko@gmail.com"
        git config --global user.name "Vladimir Migashko"
        mkdir -p build
    - name: init
      run: |
        rm -rf .github
        rm -rf cmake
        rm -rf external
        git submodule update --init external/cmake-ci
        pushd external/cmake-ci
          git checkout master
        popd
        rsync -a external/cmake-ci/root-ci/ ./
        date +"%F %X" >> ./.ci/build_history.txt
    - name: configure
      run: cd build && cmake .. -DBUILD_TESTING=ON -DPARANOID_WARNINGS=OFF
    - name: make
      run: cmake --build ./build
    - name: make check
      run: cd build && ctest
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: master
