name: C++ CI

on:
  push:
    branches:
      - mambaru

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: setup
      run: |
        sudo locale-gen ru_RU
        sudo locale-gen ru_RU.UTF-8
        sudo update-locale
        sudo apt-get install -y libboost-system-dev libboost-program-options-dev 
        sudo apt-get install -y libboost-filesystem-dev libboost-date-time-dev libboost-regex-dev
        sudo apt-get install -y doxygen lcov
        mkdir -p build
    - name: init
      run: |
        git submodule update --init external/cmake-ci
        pushd external/cmake-ci
          git checkout master
        popd
        rsync -a external/cmake-ci/root-ci/ ./
        date +"%F %X" >> ./.github/build_history.txt
        ls -l 
        ls -l ./.github/
        echo "---------------------"
        cat ./.github/build_history.txt
        git branch
        git status
        echo "====================="
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        base: master
        branch: mambaru
        branch-suffix: none
    - name: make doc
      run: make doc
    - name: make, test and coverage report
      run: |
        make coverage-report
        pushd build
          bash <(curl -s https://codecov.io/bash)
        popd
    - name: make gh-pages
      run: |
        git clone -b gh-pages https://${{ secrets.ACCESS_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git gh-pages
        pushd gh-pages
          git config --global user.email "${GITHUB_ACTOR}@https://users.noreply.github.com/"
          git config --global user.name "${GITHUB_ACTOR}"
          rsync -a --update ../docs/html/ ./
          git add --all
          COMMIT_MESSAGE="Update pages on $(date +'%Y-%m-%d %H:%M:%S')"
          git diff-index --quiet --cached HEAD -- && echo "No changes!" && exit 0 || echo $COMMIT_MESSAGE
          git commit -m "${COMMIT_MESSAGE}"
          git push https://${{ secrets.ACCESS_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git gh-pages:gh-pages
        popd
        rm -rf gh-pages
