name: C++ CI

on:
  push:
    branches:
      - mambaru

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: setup
      run: |
        sudo locale-gen ru_RU
        sudo locale-gen ru_RU.UTF-8
        sudo update-locale
        sudo apt-get install -y libboost-system-dev libboost-program-options-dev 
        sudo apt-get install -y libboost-filesystem-dev libboost-date-time-dev libboost-regex-dev
        sudo apt-get install -y doxygen lcov
        mkdir -p build
    - name: init
      run: |
        git submodule update --init external/cmake-ci
        pushd external/cmake-ci
          git checkout master
        popd
        rsync -a external/cmake-ci/root-ci/ ./
        date +"%F %X" >> ./.github/build_history.txt
    - name: make, test and coverage report
      run: make coverage-report
    - name: make doc
      run: make doc
    - name: make gh-pages
      run: |
        pushd docs/html
          git config --global user.email "${GITHUB_ACTOR}@https://users.noreply.github.com/"
          git config --global user.name "${GITHUB_ACTOR}"
          git init
          git add .
          git commit -m "doxygen" || exit $?
          echo "git push -f https://${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git master:gh-pages"
          git push -f https://${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git master:gh-pages || exit $?
        popd
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        base: master
        branch: mambaru
        branch-suffix: none
