name: C++ CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: setup
      run: |
        sudo locale-gen ru_RU
        sudo locale-gen ru_RU.UTF-8
        sudo update-locale
        sudo apt-get install -y libboost-system-dev libboost-program-options-dev 
        sudo apt-get install -y libboost-filesystem-dev libboost-date-time-dev libboost-regex-dev
        mkdir -p build
    - name: configure
      run: cd build && cmake .. -DBUILD_TESTING=ON -DPARANOID_WARNINGS=OFF -DNO_MEMCHECK=ON
    - name: make
      run: cmake --build ./build
    - name: make check
      run: cd build && ctest
    - name: push tag
      run: |
        git pull --tags
        tag=$(git describe --tags `git rev-list --tags --max-count=1`)
        echo "  tag=$tag"
        git tag --force -a $tag -m " github actions"
        git push --force --tags


